package io.kaos.agent;

/** Content-free reason for an incomplete bounded agent workflow. */
public enum AgentFailureReason {
    INVALID_GOAL,
    INVALID_PLAN,
    TOOL_NOT_ALLOWED,
    TOOL_CONFIGURATION_UNAVAILABLE,
    TOOL_VALIDATION_FAILED,
    LOCAL_FILE_TOO_LARGE,
    PERMISSION_DENIED,
    INVALID_APPROVAL,
    END_OF_INPUT,
    CANCELLED,
    INTERRUPTED,
    TOOL_EXECUTION_FAILED,
    SEARCH_SERVICE_UNAVAILABLE,
    SEARCH_TIMEOUT,
    SEARCH_INVALID_RESPONSE,
    SEARCH_RESULT_TOO_LARGE,
    TOOL_HISTORY_FAILED,
    CURRENT_EVIDENCE_UNAVAILABLE,
    MODEL_PROVIDER_FAILED,
    INVALID_TOOL_RESULT;

    public boolean cancellation() {
        return this == END_OF_INPUT || this == CANCELLED || this == INTERRUPTED;
    }
}
